%% Automate Importing Data by Generating Code Using the Database Explorer App
% This code reproduces the data obtained using the Database Explorer app by
% connecting to a database, executing a SQL query, and importing data into the
% MATLAB(R) workspace. To use this code, add the password for connecting to the
% database in the database command.

% Auto-generated by MATLAB Version 9.3 (R2017b) and Database Toolbox Version 8.0 on 07-Dec-2017 00:18:41

%% Set preferences
prefs = setdbprefs('DataReturnFormat');
setdbprefs('DataReturnFormat','table')

%% Make connection to database
conn = database('testimies12333','root','','Vendor','MYSQL','Server','localhost','PortNumber',3306);

%% Execute query and fetch results
curs = exec(conn,['SELECT Pisteet, ' ...
    '	Vuosi ' ...
    'FROM testimies12333.runkosarja_tilastot where joukkue = "TPS" AND vuosi < 1981']);
curs = fetch(curs);
data = curs.Data;
close(curs)

%% Close connection to database
close(conn)

%% Restore preferences
setdbprefs('DataReturnFormat',prefs)

%% Clear variables
clear prefs conn curs